### ISSUE TITLE
you also lost a couple of gh/s?

### ISSUE THREAD

**Issue by parabola20** [UnamSanctam/SilentCryptoMiner#1035]
what's happening? сan someone explain to me why the hashrate has dropped sharply? windows updates are disabled in the settings, everything is ok with the pool too

**Comment by UnamSanctam** [comment]
Are you able to run the checker on any of the computers? Or post a screenshot of the web panel if you have one?

**Comment by parabola20** [comment]
the first time I lost 80-90% of my hashrate when updating a defender. this problem was solved with the updated miner. I'm afraid there's something wrong here

**Comment by parabola20** [comment]
> Are you able to run the checker on any of the computers? Or post a screenshot of the web panel if you have one?

I can, but there are many of these users to deal with each. out of 8-10.5 gh/s left 6-6.5 in one night

**Comment by UnamSanctam** [comment]
Could maybe be the new detection that masterjek reported in https://github.com/UnamSanctam/SilentCryptoMiner/issues/1034, Windows Updates being disabled makes it so that Windows Defender won't reset due to an update but depending on your settings I believe you can still receive definition updates (because they aren't done by Windows Update). Are you able to check on a few of the computers if you have access and see if something similar is the case?

**Comment by parabola20** [comment]
> Could maybe be the new detection that masterjek reported in #1034, Windows Updates being disabled makes it so that Windows Defender won't reset due to an update but depending on your settings I believe you can still receive definition updates (because they aren't done by Windows Update). Are you able to check on a few of the computers if you have access and see if something similar is the case?

I don't control them. I don’t even know which users the miner works on and which ones it doesn’t. this is too much work, so I can’t say who lost the miner and who stayed. I really hope that you know your business well so as not to repeat that case with the loss of 90% of the hashrate.

**Comment by parabola20** [comment]
at the first alarm call, you need to update the remaining users so as not to lose everyone. is it possible to do it via remote configuration?

**Comment by parabola20** [comment]
I still have users from the last update, and their hashrate (200-400) did not change at night. I think it's the work of Windows Defender

**Comment by parabola20** [comment]
but what is that badass brazilian talking about? did he lose all 10 ghs at once?

**Comment by UnamSanctam** [comment]
> I don't control them. I don’t even know which users the miner works on and which ones it doesn’t. this is too much work, so I can’t say who lost the miner and who stayed. I really hope that you know your business well so as not to repeat that case with the loss of 90% of the hashrate.

Well I can't really know why people lose miners unless they tell me, and the previous new Windows update that reset Windows Defender (the big hashrate loss) wasn't really my fault or a problem with the miner either, it's just a natural part of the Windows lifecycle which is why we cut that off with "Disable Windows Update" now. But something will always happen in the future unless someone is able to convince Microsoft to stop updating Windows. I would like to be able to disable Windows Defender definition updates as well but I haven't really been able to since all those files are protected.

>at the first alarm call need to update the remaining users so as not to lose everyone. is it possible to do it via remote configuration?

No there's no remote update since you would need to uninstall it first (run the uninstaller) to be able to install a new one since the miners are more hidden now. And when I first added a remote update feature then people kept destroying their miners by uploading wrongly configured new miners and then blaming me for it.

> I still have users from the update when everything was gone, and their hashrate (200-400) did not change at night. I think it's the work of Windows Defender

Yeah then that could be it.

> but what is that badass brazilian talking about? did he lose all 10 ghs at once?

Not sure, he could just be hyperbolic, you wouldn't lose all hashrate at once unless the pool does something. He could be affected by the same Windows Defender update but he wouldn't lose all hashrate with that either. So all I can do is ask him to run the checker (since he said that has RATs on all of them) on one and see what it returns.

**Comment by parabola20** [comment]
> > I don't control them. I don’t even know which users the miner works on and which ones it doesn’t. this is too much work, so I can’t say who lost the miner and who stayed. I really hope that you know your business well so as not to repeat that case with the loss of 90% of the hashrate.
> 
> Well I can't really know why people lose miners unless they tell me, and the previous new Windows update that reset Windows Defender (the big hashrate loss) wasn't really my fault or a problem with the miner either, it's just a natural part of the Windows lifecycle which is why we cut that off with "Disable Windows Update" now. But something will always happen in the future unless someone is able to convince Microsoft to stop updating Windows. I would like to be able to disable Windows Defender definition updates as well but I haven't really been able to since all those files are protected.
> 
> > at the first alarm call need to update the remaining users so as not to lose everyone. is it possible to do it via remote configuration?
> 
> No there's no remote update since you would need to uninstall it first (run the uninstaller) to be able to install a new one since the miners are more hidden now. And when I first added a remote update feature then people kept destroying their miners by uploading wrongly configured new miners and then blaming me for it.
> 
> > I still have users from the update when everything was gone, and their hashrate (200-400) did not change at night. I think it's the work of Windows Defender
> 
> Yeah then that could be it.
> 
> > but what is that badass brazilian talking about? did he lose all 10 ghs at once?
> 
> Not sure, he could just be hyperbolic, you wouldn't lose all hashrate at once unless the pool does something. He could be affected by the same Windows Defender update but he wouldn't lose all hashrate with that either. So all I can do is ask him to run the checker (since he said that has RATs on all of them) on one and see what it returns.

it is not your fault, we should be grateful for your product, but when so much work done stops at once, we start looking for a reason and come to the developer on nerves, shouting to him about updates. sorry if it seemed like that. nevertheless, it seems to me that a remote update would have saved from the defender of windows, at least reduced the damage

**Comment by UnamSanctam** [comment]
>it is not your fault, we should be grateful for your product, but when so much work done stops at once, we start looking for a reason and come to the developer on nerves, shouting to him about updates. sorry if it seemed like that. nevertheless, it seems to me that a remote update would have saved from the defender of windows, at least reduced the damage

Yeah I understand that, it pains me when people lose their work as well.

The problem with a remote update is that for it to happen I would either have to integrate a full uninstaller into both the miners (which means I would have to pass a lot of extra information through the command line of the miners) or I would require people to both upload their old miners Uninstaller (the exact one that was created with the old miner) and the new miner. So if you have multiple builds using the same "Remote Configuration" then it wouldn't really work. Another option would be to make the miner less hidden so that any uninstaller can find the miner but that would have its own issues as well of course.

**Comment by Pedrolito666** [comment]
Me too all my miners are 0h/s for gpu

**Comment by UnamSanctam** [comment]
> Me too all my miners are 0h/s for gpu

0H/s in the web panel or your pool?

**Comment by Pedrolito666** [comment]
Both

**Comment by UnamSanctam** [comment]
> Both

Post a screenshot of your web panel.

**Comment by Pedrolito666** [comment]
![Capture d’écran 2022-08-17 à 16 31 12](https://user-images.githubusercontent.com/110937628/185162618-01a66a18-2f43-41db-8be6-fb46ec921332.jpeg)

**Comment by UnamSanctam** [comment]
>the same config worked yesterday.

Could just be out of VRAM since you're mining ETH, try changing the configuration to ETC 2miners (or UBQ) to see if you get hashrate. I don't think you have the same problem as the others.

**Comment by Pedrolito666** [comment]
Ok it's the same thing with ETC or UBQ. Maybe it's the stealth on fullscreen ?

**Comment by UnamSanctam** [comment]
No it would show in the status field if that was the case, can you set it to ETC or UBQ and screenshot that?

**Comment by Pedrolito666** [comment]
![IMG_20220817_164709](https://user-images.githubusercontent.com/110937628/185170349-83298cce-3cb3-4ced-91b6-9260ce75292d.jpg)

**Comment by Pedrolito666** [comment]
{
    "url": "stratum://`0x155921Bb211038Ffe13b4Ed3FDAF945A97d8D2Fd`.{COMPUTERNAME}@etc.2miners.com:1010",
    "algo": "etchash",
    "max-gpu": 30,
    "idle-wait": 1,
    "idle-gpu": 100,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,AnVir.exe,PLIhDBWxRt.exe,GPU-Z.exe,regedit.exe,Autoruns.exe,adwcleaner.exe,CCleaner64.exe,bitdefender.exe,kaspersky.exe,panda.exe,zoneAlarm.exe,Malwarebytes.exe,defender.exe,eset.exe,360.exe,IObit.exe",
    "kill-targets": ""
}

**Comment by Pedrolito666** [comment]
I changed back the configuration but it still show 0.

**Comment by UnamSanctam** [comment]
Interesting, that should be fine unless the VRAM is full which I guess it isn't (because it has 12GB), do you have access to the computer or not?

**Comment by Pedrolito666** [comment]
Two of them work but the others shows 0h/s even with idle.

**Comment by UnamSanctam** [comment]
Hmm, either it could be something with the VRAM or they could be laptops with the dedicated GPUs currently disabled since Nvidia hasn't activated them for anything, those specs (CPU specifically) doesn't look like a laptop though.

**Comment by Pedrolito666** [comment]
Ok so I can't do anything about it, yes all of them isn't laptop.
