### ISSUE TITLE
miner not working

### ISSUE THREAD

**Issue by parabola20** [UnamSanctam/SilentCryptoMiner#1508]
hello unam, today I tested new builds on my PC in the ETC algo, at run the miner creates an updater.exe file but does not work. when i try to run updater.exe manually then miner works. Here are my settings that I have been using since 2022. what could be the problem? links to remote configuration are also relevant

[etc 3.1.0.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/11130303/etc.3.1.0.zip)

**Comment by UnamSanctam** [comment]
Might be due to it containing spaces in the the "Entry Name", Powershell is really unfriendly so that could be the case. I am also planning on releasing the next version either today or tomorrow.

**Comment by parabola20** [comment]
> Might be due to it containing spaces in the the "Entry Name", Powershell is really unfriendly so that could be the case. I am also planning on releasing the next version either today or tomorrow.

thanks i will check
waiting for the update more than deadpool 3 :)

**Comment by UnamSanctam** [comment]
I have released the new update now and you can try building a new miner with that update if you want.

**Comment by parabola20** [comment]
> Might be due to it containing spaces in the the "Entry Name", Powershell is really unfriendly so that could be the case. I am also planning on releasing the next version either today or tomorrow.

I'm testing a new version now, I decided to enable the rootkit, but this error occurs every time I create a build
![photo_2023-04-02_14-40-05](https://user-images.githubusercontent.com/94918344/229348041-e29e15b2-ac5f-49e1-927b-a5d4f05858f8.jpg)

**Comment by parabola20** [comment]
the build is created on disk C, there are no Russian characters in the path)

**Comment by UnamSanctam** [comment]
And you started it with administrator privileges (since C: requires that)?

**Comment by parabola20** [comment]
> And you started it with administrator privileges (since C: requires that)?

yep, my mistake. but the miner still doesn't work for me. the file is being created, but there is no load...

my new settings: without spaces: [etc 3.2.0.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/11131972/etc.3.2.0.zip)

![photo_2023-04-02_14-50-04](https://user-images.githubusercontent.com/94918344/229348477-6fcb9e12-f9ba-41ce-b9fa-5ff4c16ed8df.jpg)

**Comment by UnamSanctam** [comment]
Does it say that the miner is running if you run the checker? Can you set up a local web panel and connect the miner to that to see what it's doing?

**Comment by parabola20** [comment]
> Does it say that the miner is running if you run the checker? Can you set up a local web panel and connect the miner to that to see what it's doing?

the checker does not show the miner. I haven’t figured out the panel yet, I’m trying to create builds with other settings

**Comment by UnamSanctam** [comment]
If you try the example settings then does it show any miner https://github.com/UnamSanctam/SilentCryptoMiner/wiki#lite?

**Comment by parabola20** [comment]
> If you try the example settings then does it show any miner https://github.com/UnamSanctam/SilentCryptoMiner/wiki#lite?

works, only the load graph went in a zigzag, I don’t know how correct it is. apparently the problem is in my settings, although I always used them and got a lot of ghs

![photo_2023-04-02_15-07-56](https://user-images.githubusercontent.com/94918344/229349172-d79f1540-ba43-4473-a6cf-952fdf7af536.jpg)

**Comment by UnamSanctam** [comment]
The zigzag is just due to the polling interval of your MSI Afterburner not being long enough for your GPUs mining search time, it's normal for older GPUs since they aren't as fast. Not sure what the exact problem was with your settings, it's hard to tell. You can try modifying the example settings into your settings in steps until it stops working.

**Comment by parabola20** [comment]
> The zigzag is just due to the polling interval of your MSI Afterburner not being long enough for your GPUs mining search time, it's normal for older GPUs since they aren't as fast. Not sure what the exact problem was with your settings, it's hard to tell. You can try modifying the example settings into your settings in steps until it stops working.

good idea, i'm working on it

**Comment by parabola20** [comment]
> > The zigzag is just due to the polling interval of your MSI Afterburner not being long enough for your GPUs mining search time, it's normal for older GPUs since they aren't as fast. Not sure what the exact problem was with your settings, it's hard to tell. You can try modifying the example settings into your settings in steps until it stops working.
> 
> good idea, i'm working on it

no matter what I change, the miner does not start. if I run the updater.exe on my own, then it starts mining. the build seems to be unable to run it

**Comment by UnamSanctam** [comment]
But the example settings work fine? I have tried the example settings on probably 30-40 different computers (asked people over mail) and VMs over the last few days and those have always worked so those should work fine. If it's not the example settings then did you change it like I said in the previous post? In that case what did you change overall?

**Comment by parabola20** [comment]
> But the example settings work fine? I have tried the example settings on probably 30-40 different computers (asked people over email) and VMs over the last few days and those have always worked so those should work fine. If it's not the example settings then did you change it like I said in the previous post? In that case what did you change overall?

I tried to change all the settings, removed the remote configuration, changed the path, icons, autorun settings, but I still did not understand where my mistake was

**Comment by UnamSanctam** [comment]
So do the example settings work or not (since they were working for you before I'm asking whether they stopped working or  not)? And does it stop working after you modify the example settings to be like your settings? I've tried your settings and they work fine for me on my main computer, another computer and also my VM.

**Comment by parabola20** [comment]
> So do the example settings work or not (since they were working for you before I'm asking whether they stopped working or not)? And does it stop working after you modify the example settings to be like your settings? I've tried your settings and they work fine for me on my main computer, another computer and also my VM.

try to remove in the [ExampleSettings_Full.zip](https://github.com/UnamSanctam/SilentCryptoMiner/files/11132383/ExampleSettings_Full.zip) XMR algorithm from your instance. i did this and the remaining ETC miner stopped running. the miner worked under the condition of assembly with two algorithms

**Comment by parabola20** [comment]
on my machine, forgot to add.

**Comment by parabola20** [comment]
I also tested the build with my settings on the user in the rat. it worked exactly like mine - after launch, the updater.exe file was created and the miner started working only after opening this file :(

**Comment by UnamSanctam** [comment]
Hmm if I remove XMR then the ETC miner start like it should for me, if you disable "Run as System" does it work for you then?

**Comment by UnamSanctam** [comment]
Could you try rebuilding the miner a few times and see if it any of them work? Potentially the problem could maybe be due to some random string.

**Comment by parabola20** [comment]
> Hmm if I remove XMR then the ETC miner start like it should for me, if you disable "Run as System" does it work for you then?

disabling "run as system" and changing the path to appdata helped, the miner now works stably on several PCs. can i work with these settings? how did disconnecting from the system affect the work of the miner?

**Comment by UnamSanctam** [comment]
It means that it cannot run on all users, only the user that it was installed on. If you try enabling "Run as System" again does it stop working for you?

**Comment by parabola20** [comment]
> It means that it cannot run on all users, only the user that it was installed on. If you try enabling "Run as System" again does it stop working for you?

yes, and on other PCs in the rat which I checked

**Comment by UnamSanctam** [comment]
Hmm, I'm not able to recreate the problem, does it only happen for ETC for you? If you have both XMR+ETC or only XMR does the problem also happen?

**Comment by parabola20** [comment]
> Hmm, I'm not able to recreate the problem, does it only happen for ETC for you? If you have both XMR+ETC or only XMR does the problem also happen?

I'm also confused about what's going on. xmr+ etc with your settings works for me, as soon as I delete xmr and leave one etc, it doesn't work again

**Comment by parabola20** [comment]
I tried to run exactly the same settings as you, only with my address, it didn't work without xmr

**Comment by UnamSanctam** [comment]
This is a really strange problem, I have been testing a ton of builds and done a lot of debugging and maybe a possible reason that it's working for me and not for you (and your client) could be due to some sort of possible memory problem or issue with null terminators inside the GPU checking function. Could you try this build and see if that works normally for you: https://anonfiles.com/NcN4A1iaza/Silent_Crypto_Miner_Builder_zip?

**Comment by svox07** [comment]
> > unam hello miner 3.2.0 после получаса простоя примерно пк установил майнер запускается пк ничего не реагирует иногда ошибки вылетает Microsoft Edge или winlogan Windows 10 делал переустановку 3 раза для теста но все равно бывает от чего может быть эта проблема я предполагаю это происходит когда майнер освобождает память от этого происходит сбой или это руткит
> 
> Не совсем уверен, в чем проблема, но вы можете попробовать отключить руткит. Поскольку теоретически это может вызвать некоторые проблемы на компьютерах, чьи системы несколько повреждены или если на них есть программы, которые могут блокировать что-то.

this does not happen immediately if the computer is idle for about 20-30 minutes, the desktop hangs up like this, maybe the antivirus is blocking the rootkit?  but the antivirus does not show any messages

**Comment by UnamSanctam** [comment]
>3 different assemblies of Windows freshly installed Windows hardware is different, but it happens to check for yourself it doesn’t hang right away, but after about 30 minutes, if you don’t move the mouse, then this happens

I have it running on 2 (real) computers right now (using the Lite example settings) that are fully idle and will report back in 45 minutes (it has already been running for 15 minutes).

**Comment by parabola20** [comment]
> > it works with my old config (run as system). what did you change that led to the result? :)
> 
> I changed the registry sub key UNCODE_STRING initialization on this line:
> 
> https://github.com/UnamSanctam/SilentCryptoMiner/blob/8caef3eec1040ddb982574ccd7cc3d88016f7c09/SilentCryptoMiner/Resources/Code/Includes/common.cpp#L156
> 
> from using the definition to instead doing it manually. It seems like on some systems the registry call might incorrectly not return any null terminator in the wchar pointer which leads the length counter to be inaccurate. I "simply" changed the line to this instead:
> ```
> regKey.Buffer = ((PKEY_BASIC_INFORMATION)subKeyBuffer)->Name;
> regKey.Length = (USHORT)((PKEY_BASIC_INFORMATION)subKeyBuffer)->NameLength;
> regKey.MaximumLength = regKey.Length;
> ```
> 
> Solving this problem felt like I was doing an 8x8 Rubik's cube blindfolded (especially since I could not test it myself so I had to guess what the problem might be) but if it is fully working for you then thankfully that should be solved now.

thanks, you are a genius!

**Comment by svox07** [comment]
> > 3 разные винды свежеустановленная винда железо разное, но бывает проверить на себе виснет не сразу, через 30 минут если не шевелить мышкой то такое происходит
> 
> Хм, оба компьютера уже более 1 часа простаивают, и у меня все работает как обычно. Можете ли вы попробовать с настройками примера и посмотреть, получится ли это https://github.com/UnamSanctam/SilentCryptoMiner/wiki#example-settings ?

right now I’m testing in places explorer put conhost I’ll see what happens and windows defender is not observed only avg antivirus means avg blocks something but avg doesn’t give any warning right now I’m doing tests when I finish I’ll let you know Unam

**Comment by svox07** [comment]
I tested RootKit reason with third party antivirus I tested Avast and Avg miner is not detected but with RootKit pc starts to freeze Defender has no such problems also tested without Rootkit everything works fine output by third party antivirus Rootkit Windows starts to freeze

**Comment by UnamSanctam** [comment]
>I tested RootKit reason with third party antivirus I tested Avast and Avg miner is not detected but with RootKit pc starts to freeze Defender has no such problems also tested without Rootkit everything works fine output by third party antivirus Rootkit Windows starts to freeze

Alright so the problems only occur when there are third-party antiviruses such as Avast and AVG on the computer? Those kinds of antiviruses usually have things like anti-rootkits and they also restrict a lot of the operating system so that's probably a really difficult (if even possible at all) problem to fix then. I'll try to see if I can recreate it at all, and if I can then I'll try and see if it's possible to do anything about it.

**Comment by UnamSanctam** [comment]
>the previous version of miner 3.1.0 did not have such problems, the new version breaks various Windows services, especially Winlogan.exe from this, Windows freezes precisely with third-party antiviruses, it only breaks with the standard antivirus, there are no such problems

You mean with the rootkit? The rootkit hasn't really been changed in any way except that it now gets injected directly. Can you take a video of this happening? I'm not able replicate it on any computer I try it on. And winlogon.exe isn't a service, if something break winlogon then the computer will immediately BSoD which doesn't sound like it's happening so most likely it's due to something else.

**Comment by svox07** [comment]
> > у предыдущей версии майнера 3.1.0 таких проблем не было, новая версия ломает разные службы винды, особенно Winlogan.exe от этого, зависает винда именно со сторонними антивирусами, ломается только штатным антивирусом, таких нет проблемы
> 
> Вы имеете в виду только с включенным руткитом? Руткит на самом деле не претерпел никаких изменений, за исключением того, что теперь он внедряется напрямую, так что функционально я не думаю, что он должен слишком сильно меняться. Можешь снять видео происходящего? Я не могу воспроизвести это на любом компьютере, на котором я пытаюсь это сделать. И winlogon.exe не является службой, если что-то сломает winlogon, компьютер немедленно выдаст BSoD, что не похоже на то, что это происходит, поэтому, скорее всего, это связано с чем-то другим.

I disabled Bsod miner when disabling the rootkit, I don’t observe such problems, 3 different Windows were also tested

**Comment by UnamSanctam** [comment]
>I disabled Bsod miner when disabling the rootkit, I don’t observe such problems, 3 different Windows were also tested

I'm guessing that if the miner works with rootkit enabled with Avast and AVG installed in the previous version but not this one then the reason would be that in the previous version Avast and AVG is removing the rootkit before it completes the installation. But in the new version it probably starts the rootkit before it gets detected, so then the problem would technically be that the new miner version is better than the old one.

And does everything work correctly with the rootkit disabled? In that case you can disable the rootkit and use that. It sounds like the freezing is caused by Avast and AVG doing things to the rootkit, and the possible reason that it does not happen in the previous version is that the rootkit was easier to detect then so that Avast and AVG could remove it before the rootkit could start.

**Comment by svox07** [comment]
> > Отключил Bsod miner при отключении руткита, таких проблем не наблюдаю, тестировалось также на 3-х разных виндах
> 
> Я предполагаю, что если майнер работает с включенным руткитом с Avast и AVG, установленными в предыдущей версии, но не в этой, то причина будет заключаться в том, что в предыдущей версии Avast и AVG удаляют руткит до завершения установки. Но в новой версии он, вероятно, запускает руткит до того, как его обнаружат, поэтому технически проблема будет заключаться в том, что новая версия майнера лучше старой.
> 
> А с отключенным руткитом все работает корректно? В этом случае вы можете отключить руткит и использовать его. Похоже, что зависание вызвано тем, что Avast и AVG делают что-то с руткитом, и возможная причина того, что этого не происходит в предыдущей версии, заключается в том, что тогда руткит было легче обнаружить, чтобы Avast и AVG могли удалить его раньше, чем руткит. мог начать.



> > I disabled Bsod miner when disabling the rootkit, I don’t observe such problems, 3 different Windows were also tested
> 
> I'm guessing that if the miner works with rootkit enabled with Avast and AVG installed in the previous version but not this one then the reason would be that in the previous version Avast and AVG is removing the rootkit before it completes the installation. But in the new version it probably starts the rootkit before it gets detected, so then the problem would technically be that the new miner version is better than the old one.
> 
> And does everything work correctly with the rootkit disabled? In that case you can disable the rootkit and use that. It sounds like the freezing is caused by Avast and AVG doing things to the rootkit, and the possible reason that it does not happen in the previous version is that the rootkit was easier to detect then so that Avast and AVG could remove it before the rootkit could start.

I confirm with the rootkit disabled Avast and Avg work well the first time you start the miner it gives a warning but does not block Miner also works after Windows reboot the second time it does not give a warning Avast and Avg means the miner is well hidden

**Comment by UnamSanctam** [comment]
>I confirm with the rootkit disabled Avast and Avg work well the first time you start the miner it gives a warning but does not block Miner also works after Windows reboot the second time it does not give a warning Avast and Avg means the miner is well hidden

Alright that's great, I'll just have to try and see if I can make the rootkit work without Avast or AVG interfering in some way with it.
