### ISSUE TITLE
miners stop working after restart

### ISSUE THREAD

**Issue by jamiekarvans** [UnamSanctam/SilentCryptoMiner#1517]
hi i used a few version older and that still is working for me with no problem but since these a few new updates the miner is not presistant and will stop working, also it does not show in the web panel
and i wanted to ask you how much gpu is needed for etc to mine using this miner? because in most clients i run the miner with full example settings the xmr miner works fine but etc gpu mining does not work and maybe 2/10 of clients show in 2miners site but xmr is ok
so i thought maybe there is a gpu limitation and if so then what is best coin to mine for lesser gpus

**Comment by UnamSanctam** [comment]
Both the startup and web panel should be working fine, I've tested it at least a few thousand times just for this version. Make sure that your settings are correct, if you use the example settings then it should work right out of the gate. To mine ETC around 3.2GB of VRAM is currently required (the coin itself requires that, so all miners need to use that much), UBQ uses less VRAM at around 1.9GB but it can be harder to sell unless you understand swaps and how to move things across chains, you can see how much VRAM different coins require here: https://minerstat.com/dag-size-calculator. There is also a wiki entry about it here: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#what-gpu-requirements-are-there-for-the-gpu-miners-to-work.

**Comment by jamiekarvans** [comment]
thanx for fast replying
yes that probably was the problem
do you know which pool is recommended for UBQ to setup in miner and with what algorithm

**Comment by UnamSanctam** [comment]
You can find all the pools here: https://miningpoolstats.stream/ubiq but picopool is probably the most popular since that's just nanopools other site and nanopool does not really ban for having a lot of miners (which some pools do). UBQ uses the `ubqhash` algorithm inside the miner.

**Comment by jamiekarvans** [comment]
thanx and is this the right format for wallet in picopool?
WalletAddress.WorkerName/WithdrawalPassword

**Comment by jamiekarvans** [comment]
yes it's working perfectly and the problem was the GPU ram which was causing the issue
but the web panel problem still presist,
my url is like this http://website.com/UnamSanctam/api/endpoint.php
and i added this exactly to end point api
is this why ii'm facing the issue ? becasue the data is in the unamsanctam folder

**Comment by UnamSanctam** [comment]
And you're sure that your website isn't force redirecting to https or anything like that (since I assume you don't have a certificate)?

**Comment by jamiekarvans** [comment]
no it's not redirecting also i have no ssl and the url is http 
i updated 20 clients but none of them showing in webpanel

**Comment by UnamSanctam** [comment]
Check your webserver logs to make sure it's not blocking the connections, or you can also check the access logs to see if it's accepting connections at all. The only reason why it wouldn't show up on the web panel is really either 1) database isn't writable 2) something wrong with the hosting (for example connection being rejected) or 3) URL is wrong. Since you say that 3) isn't the case then it's either due to 1) or 2). To test if the database is writable then you can try creating a new configuration inside "Configurations", if you can do that then the database should be writable. To know if 2) is the problem you'll have to check the logs.

**Comment by jamiekarvans** [comment]
thanx for the help, i checked all of them and there was nothing in log file, and no connection was being rejected, idk where is the problem but i gave up on it and now just using the remote configiration, thanx for your help and care

also i wanted to know do you recommend mining Dero using the older versions of UnamSantcam miner? because it looks alot more pofitable than mining xmr

**Comment by UnamSanctam** [comment]
>thanx for the help, i checked all of them and there was nothing in log file, and no connection was being rejected, idk where is the problem but i gave up on it and now just using the remote configiration, thanx for your help and care
also i wanted to know do you recommend mining Dero using the older versions of UnamSantcam miner? because it looks alot more pofitable than mining xmr

Don't think you can mine Dero using the old version anymore, I think they forked to AstroBTW/v3. And from what I understand Dero is less profitable than Monero at the moment.

**Comment by jamiekarvans** [comment]
thanx alot for the help 
i still can not find the issue with the miner, how can i pinpoint the issue? is there a log file?
i have about 10 new clients everyday and the miner runs with no error but there is no mining happening in most of the PCs maybe only 5/10 of PCs run and mine correctly and report to 2miners.com
the windows defender is also disabled 
i first thought maybe it can not connect to 2miners.com but i'm not sure since it pings to server without issue
is there any options that if i turn off or on that will make the miner more versetile and more stable?
clients running mostly windows 10 64 bit

**Comment by UnamSanctam** [comment]
You mean that 5/10 mine XMR to 2miners? The miner uses xmrig which in itself is the best XMR miner , the only real way to get "in-depth" information is to use the web panel. It could be a multitude of reasons for them not showing up, such as not enough RAM for RandomX, not enough cache in the CPU, not enough cores available, a "Stealth Target" program being open, not being able to connect to the pool for any reason, some computers having the same computer name (not common but it depends what kind of clients you have) or the statistics just looking weird if the computers hashrate isn't that high compared to the share difficulty (120 000 for 2miners XMR).

For ETC specifically then the reason could be a lack of a good enough GPU or there not being enough VRAM.

**Comment by jamiekarvans** [comment]
I have checked all of these and computers that I tested have all atleast 6 gig of ram and a good cpu so there should be no problem, but still not working, I've checked the directory and the updater.exe has dropped in the program files with no problem but still no mining happened on most PCs,
But I was tweaking with settings and i disabled the run as system in startup tab and then the stub was working perfectly, I still don't know why it was causing the issue but I thought I should just let you know about it
And thanx alot for your help
